name: testing
on: [push]
jobs:
  compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make -C philo/
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: '.'